name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Step 3: Restore dependencies for the entire solution
    - name: Restore dependencies
      run: dotnet restore ProductAPI.sln

    # Step 4: Build the solution
    - name: Build
      run: dotnet build ProductAPI.sln --no-restore --configuration Release

    # Step 5: Run tests 
    - name: Test
      run: dotnet test ./tests/ProductAPI.Test/ProductAPI.Test.csproj --filter "Category!=Integration" --verbosity normal --logger "trx;LogFileName=TestResults.trx" --results-directory "TestResults"

    # Step 6: Publish Test Results
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: TestResults/TestResults.trx
